### ISSUE TITLE
Delete your fsd-setup folder

### ISSUE THREAD

**Issue by asp2131** [ntierney25/ntierney25.github.io#1]
Delete your fsd-setup folder. You can do that by running this command in your terminal `rm -rf ./fsd-setup`.

**Comment by asp2131** [comment]
After that, repush to github. If you don't remember how, you can find the commands [here](https://github.com/OperationSpark/fsd-setup#to-push-code)

**Comment by ntierney25** [comment]
I think I fixed it, thank you!

**Comment by asp2131** [comment]
@ntierney25 It still showing in your [repo](https://github.com/ntierney25/ntierney25.github.io)

**Comment by ntierney25** [comment]
I'll try and get to it today and I'll email if I have any questions.

**Comment by ntierney25** [comment]
I've finished the website, so I think everything is fine. If the issue
persists, can you email me? Thank you!
